#%RAML 1.0
title: Session REST API
version: v1
baseUri: https://session.api.ftbl.com/
mediaType: application/json

/sessions:
  post:
    body:
      authentication:
        provider: 
          description: facebook, twitter, email, verify supported
          type: string
          required: true
        token:
          type: string
        secret:
          type: string

    responses:
      200:
      
  /{id}:

    get:
      responses:
        200:

    put:
      responses:
        200:

    delete:
      responses:
        200:
